# conda env create -f environment.yml
name: flower
channels:
  - conda-forge
dependencies:
  - python=3.12
  - xarray
  - matplotlib
  - cartopy
  - numpy
  - requests
  - pandas
  - rioxarray
  - rasterio
  - tqdm
  - scikit-learn
  - scikit-image
  - geopandas
  - Pillow
  - click
  - arosics
  - planet
  - werkzeug
  - dash
  - plotly
  - pytorch
  - torchvision
  - pycocotools
  - wandb
  - torchmetrics
  - pip:
      - python-ffmpeg
