
# Directory Structure

root_dir: '/Volumes/Earth02/flower'
crown_subdir: 'crown_images_500'
crown_output_subdir: 'crown_images_500_videos'


# Script Configuration Files

config_video: 'config/crown_video.yml'
