
# Directory Structure

root_dir: '/Volumes/Earth03/flower'
crown_subdir: 'crown_images_20240513'
crown_output_subdir: 'crown_images_20240513_videos'
planet_subdir: 'planet'
planet_downloads_subdir: 'planet_bci_orders'


# Script Configuration Files

config_video: 'config/crown_video.yml'
